socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/bffbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home_view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include("profiles.urls", namespace="profiles")),
    path('posts/', include("posts.urls", namespace="posts"))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/posts/urls.py
from django.urls import path
from .views import post_comment_create_list_view, like_unlike_post, PostDeleteView, PostUpdateView, CommentDeleteView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_list_view, name='main-post-view'),
    path('liked', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('comment/<pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
]   

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile


# Create your models here.
class Post(models.Model):
    content = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='posts', validators=[FileExtensionValidator(['png','jpeg','jpg'])], blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):#will show the content in a readable string format
        return str(self.content[:20])

    def num_likes(self):#to get the number of likes
        return self.liked.all().count()

    def num_comments(self):#to get the number of comments
        return self.comment_set.all().count()

    class Meta:#arranging the post
        ordering = ('-created',)

class Comment(models.Model):
    user = models.ForeignKey(Profile,  on_delete=models.CASCADE)#this user have a many to one relationship with the Profile. The user will have a a profile
    post = models.ForeignKey(Post,  on_delete=models.CASCADE)#this means that many post or comment can be created in one Post 
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return str(self.pk)

LIKE_CHOICES = {
    ('Like', 'Like'),
    ('Unlike', 'Unlike')
}#tuple
class Like(models.Model):
    user = models.ForeignKey(Profile,  on_delete=models.CASCADE)
    post = models.ForeignKey(Post,  on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/posts/forms.py
from django import forms
from .models import Post, Comment


class PostModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':2}))#this creates the form for post
    
    class Meta:
        model = Post
        fields = {'content','image'}#in our form we have two form fields that is the content part and the image part

class CommentModelForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Add a comment...'}))
    
    class Meta:
        model = Comment
        fields = {'body',}

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .models import Post, Like, Comment
from profiles.models import Profile
from .forms import PostModelForm, CommentModelForm
from django.views.generic import UpdateView, DeleteView
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

@login_required#middle ware to protect our view so that unauthorized users cannot access them.
def post_comment_create_list_view(request):
    qs = Post.objects.all() #Querying all the objects from the post model
    profile = Profile.objects.get(user=request.user) #Querying the user profile from the Profile model

    # initials
    p_form = PostModelForm() #calling the postmodelform and creating an instance
    c_form = CommentModelForm() #calling the commentmodelform and creating an instance
    post_added = False #this is a boolean 

    # profile = Profile.objects.get(user=request.user)

    if 'submit_p_form' in request.POST: #if the user submit the post form do the internal logic
        print(request.POST)
        p_form = PostModelForm(request.POST, request.FILES)#Passing the user data as a parameters
        if p_form.is_valid():#if the form is valid do the internal logic
            instance = p_form.save(commit=False) #create an instance variable but we are not saving the form since we do not know who the author is 
            instance.author = profile#assigning the author as the owner of this profile 
            instance.save()#Saving the form
            p_form = PostModelForm()#Calling the postmodel form so that our post form is empty again
            post_added = True#setting our boolean to true

            return redirect("posts:main-post-view")#redirecting the user to the main-post-view

    if 'submit_c_form' in request.POST:
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instance = c_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            c_form = CommentModelForm()

            return redirect("posts:main-post-view")


    context = {
        'qs': qs,
        'profile': profile,
        'p_form': p_form,
        'c_form': c_form,
        'post_added': post_added,
    }#passing a dictionary to the template so that we can access the data later, using their keys

    return render(request, 'posts/main.html', context)#render the main.html template

@login_required
def like_unlike_post(request):
    user = request.user#storing the user as the user who is using the browser now 
    if request.method == 'POST':
        post_id = request.POST.get('post_id')#this gets or identifies which post is being liked 
        post_obj = Post.objects.get(id=post_id)#this gets the post 
        profile = Profile.objects.get(user=user)#this gets the profile of the user who liked the post

        if profile in post_obj.liked.all():#check whether this profile exists in the liked column 
            post_obj.liked.remove(profile)
        else:#else add the profile in the liked column
            post_obj.liked.add(profile)

        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

        if not created:
            if like.value=='Like':#if the user gave like then change the text to unlike 
                like.value='Unlike'
            else:
                like.value='Like'
        else:
            like.value='Like'

            post_obj.save()
            like.save()

    return redirect('posts:main-post-view')

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post#this implies that we are working with the post model
    template_name = 'posts/confirm_del.html'#the template is confirm_del.html
    success_url = reverse_lazy('posts:main-post-view')#if the logic is successful take the user to this url
    # success_url = '/posts/'

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')#we are getting the primary key of the post which the user wants to delete
        obj = Post.objects.get(pk=pk)#we are getting the post by using the pk
        if not obj.author.user == self.request.user:#if the user that is requesting to delete this post is not the author of this post then show him a warning
            messages.warning(self.request, 'You need to be the author of the post in order to delete it')
        return obj#return the post

class PostUpdateView(LoginRequiredMixin, UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:main-post-view')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, "You need to be the author of the post in order to update it")
            return super().form_invalid(form)


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'posts/confirm_del.html'
    success_url = reverse_lazy('posts:main-post-view')
    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Comment.objects.get(pk=pk)
        if not obj.user.user == self.request.user:
            messages.warning(self.request, 'You need to be the author of the comment in order to delete it')
        return obj

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/posts/templates/posts/confirm_del.html
{% extends 'base.html' %}
{% block title %}Delete posts{% endblock title %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if 'warning' in message.tags %}
                    <div class="header">
                        {{message}}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% else %}
        <div class="ui segment"style="color: white;background-color:#363062;">
            <h3>Delete Post ?</h3>
            <form action="" method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete this post ??</p>
                <button class="ui secondary button"type="submit">Delete</button>
            </form>
        </div>
    {% endif %}
{% endblock content %}

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/posts/templates/posts/main.html
{% extends 'base.html' %}

{% block title %}main page{% endblock title %}

{% block content %}
<div class="ui one column stackable page grid">
    <div class="column twelve wide">
            <div class="ui segment" style="color: white; background-color:#363062;">
                {% if post_added %}
                    <div class="ui green message">Post added</div>
                {% endif %}
                <form action="" method="POST" class='ui form' style="background-color:#363062;"enctype="multipart/form-data">
                    {% csrf_token %}
                        {{p_form}}
                    <button type='submit' name="submit_p_form" class="ui positive button w-full mt-5">Post</button>
                </form>
            </div>
        {% for obj in qs %}

        <div class="ui fluid card">
            <div class="content" style="color: white; background-color:#363062;">
                <div class="right floated meta">
                    <div class="ui grid">
                        {% ifequal request.user obj.author.user %}
                        <span><a href="{% url 'posts:post-update' obj.pk %}"><button class="ui button bwhite-lg ">Update</button></a></span>
                        <span><a href="{% url 'posts:post-delete' obj.pk %}"><button class="ui button bwhite-lg ">Delete</button></a></span>
                        {% endifequal %}
                    </div>    
                </div>
                <img class="ui avatar image" src={{obj.author.avatar.url}}> 
                {{ obj.author.user }} - {{ obj.created|timesince}} ago
            </div>
            <div class="ui fluid image" style="background-color:#363062;">
                {% if obj.image %}
                    <img src={{obj.image.url}}>
                {% endif %}
            </div>
            <div class="content" style="color: white; background-color:#363062;">
                <h5 style="font-family:Arial, Helvetica, sans-serif; font-size: larger;"> {{ obj.content|safe }} </h5>
                <div class="right floated">
                    <form action="{% url 'posts:like-post-view' %}" method="POST" class='like-form' id='{{obj.id}}'>
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value={{obj.id}}>
                        
                            <button type="submit" class="ui black button like-btn{{obj.id}}">
                                {% if profile not in obj.liked.all %}
                                    Like
                                {% else %}
                                    Unlike
                                {% endif %}
                            </button>
                    </form>
                </div>
                <i class="comment blue icon" ></i>
                <span> {{ obj.num_comments }} comments</span>
                <i class="heart red icon"></i>
                <span class="like-count{{obj.id}}"> {{obj.num_likes}} icon</span>
            </div>
            <div class="extra content" style="background-color:#4D4C7D;">
                <button class="cmt_btn ui basic button" style="background-color:#827397;">show / hide comments</button>
                <div class="comment-box">
                {% if obj.comment_set.all %}
                    {% for c in obj.comment_set.all %}
                    
                        <div class="ui segment" style="color: white;background-color:#363062;">
                            <img class="ui avatar image" src={{c.user.avatar.url}}>
                            <span>{{ c.user.user }} - {{ c.created|timesince}} ago</span>
                            <div class='mt-5'>{{ c.body }}</div>
                                {% ifequal request.user c.user.user %}
                                    <span><a href="{% url 'posts:comment-delete' c.pk %}"><button class="ui button bwhite-lg ">Delete</button></a></span>
                                {% endifequal %}
                        </div>
                    
                    {% endfor %}
                {% endif %}
                </div>
  
                <form action="" method="POST"class='ui fluid form'>
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value={{obj.id}}>
                    {{ c_form }}
                    <button type="submit" name="submit_c_form" class="ui black button mt-5 w-full">Comment</button>
                </form>
            </div>
        </div>

        {% endfor %}
    </div>
    
</div>
{% endblock content %}

{% block scripts %} 
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }  
            });
            //this is the js which controls the show and hide comment button

            $('.like-form').submit(function(e){
                e.preventDefault()//prevents refresh
                
                const post_id = $(this).attr('id')//this gets the post id 
                
                const likeText = $(`.like-btn${post_id}`).text()//this get the text value ie either like or unlike
                const trim = $.trim(likeText)//this is for cleaning the data triming off blank spaces

                const url = $(this).attr('action')//
                
                let res;
                const likes = $(`.like-count${post_id}`).text()//like counter
                const trimCount = parseInt(likes)//converting the string to integer
                
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'post_id':post_id,
                    },//we are matching the csrf token and passing the post id 
                    success: function(response) {
                        if(trim === 'Unlike') {
                            $(`.like-btn${post_id}`).text('Like')
                            res = trimCount - 1
                        } else {
                            $(`.like-btn${post_id}`).text('Unlike')
                            res = trimCount + 1
                        }

                        $(`.like-count${post_id}`).text(res)
                    },
                    error: function(response) {
                        console.log('error', response)
                    }
                })

            })
        });
    </script>
{% endblock scripts %}

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/posts/templates/posts/update.html
{% extends 'base.html' %}

{% block title %}update posts{% endblock title %}

{% block content %}
    <div class="ui segment"style="color: white;background-color:#363062;">
        <h3>Update post</h3>
        <form action="" method="post" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
        <button type="submit" class="ui button primary mt-5">Update</button>
        </form>
    </div>
{% endblock content%} 