socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/bffbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home_view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include("profiles.urls", namespace="profiles")),
    path('posts/', include("posts.urls", namespace="posts"))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/posts/urls.py
from django.urls import path
from .views import post_comment_create_list_view, like_unlike_post, PostDeleteView, PostUpdateView, CommentDeleteView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_list_view, name='main-post-view'),
    path('liked', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('comment/<pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
]   

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view, 
    invites_received_view, 
    ProfileListView, 
    ProfileDetailView,
    invite_profiles_list_view,
    send_invitation,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    friends,
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name="all_profile_view"),
    path('myprofile/', my_profile_view, name="my_profile_view"),
    path('my-invites/', invites_received_view, name="my_invites_view"),
    path('to-invite/', invite_profiles_list_view, name="invite_profile_view"),
    path('send-invite/', send_invitation, name="send_invite"),
    path('remove-friend/', remove_from_friends, name="remove-friend"),
    path('<slug>', ProfileDetailView.as_view(), name="profile_detail_view"),  
    path('accept/', accept_invitation, name="accept_invitation"),
    path('reject/', reject_invitation, name="reject_invitation"), 
    path('friends/', friends, name="friends_list"),
]

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.shortcuts import reverse
# Create your models here.

class ProfileManager(models.Manager):
    
    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        print(qs)

        accepted = []
        for rel in qs:
            if rel.status == 'accepted':
                accepted.append(rel.receiver)
                accepted.append(rel.sender)
        print(accepted)

        available = [profile for profile in profiles if profile not in accepted]
        print(available)
        return available

    
    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles
        
class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True) 
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="No bio", max_length=300)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(default='avatar.png', upload_to='')
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()
    
    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse("profiles:profile_detail_view", kwargs={"slug": self.slug})

    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def get_posts_no(self):
        return self.posts.all().count()

    def get_all_authors_posts(self):
        return self.posts.all()

    def get_likes_given_no(self):
        Likes = self.like_set.all()
        total_liked = 0
        for item in Likes:
            if item.value == 'Like':
                total_liked += 1
            return total_liked

    def get_likes_recieved_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name  = self.last_name



    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug =="":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name)+ " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

STATUS_CHOICES = [
    ('send', 'send'),
    ('accepted', 'accepted')
]


class RelationshipManager(models.Manager):
    def invitations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs



class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/profiles/forms.py
from django import forms
from .models import Profile

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = {'bio','first_name','last_name','avatar'}

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
@login_required
def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():#if the user enters the correct data then save the form
            form.save()
            confirm = True


    context = {
        'profile':profile,
        'form': form,
        'confirm': confirm
    }#pass all these data to the template

    return render(request, 'profiles/myprofile.html', context)

@login_required
def invites_received_view(request):
    profile = Profile.objects.get(user=request.user)#get the profile of this user 
    qs = Relationship.objects.invitations_received(profile) #get the number of invitations received by this profile
    results = list(map(lambda x: x.sender, qs)) #create a list 
    is_empty = False
    if len(results) == 0:#check whether our list is empty or not
        is_empty = True#if it is 0 then set the counter to true
    context = {
        'qs':results,
        'is_empty': is_empty
    }#pass the list and whether it is empty or not 

    return render(request, 'profiles/my_invites.html', context)

@login_required
def friends(request):
    qs = Profile.get_friends(request.user)
    context = {
        'qs':qs
    }
    return render(request, 'profiles/friends.html', context)

@login_required
def accept_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')#get the id of the profile who is sending a request
        sender = Profile.objects.get(pk=pk)#get the profile of the sender using his pk
        receiver = Profile.objects.get(user=request.user)#get the profile of the user to whom the invitation is to be send 
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)#check whether both the user exists or not, or whether the relationship can be established or not 
        if rel.status == 'send':#if they exist and if their relationship status is send 
            rel.status = 'accepted'#then change it to accepted
            rel.save()
    return redirect('profiles:my_invites_view')

@login_required
def reject_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:my_invites_view')

@login_required
def invite_profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)#this will get all the user excluding the user

    context = {
        'qs':qs,
    }

    return render(request, 'profiles/to_invite_list.html', context)


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'profiles/detail.html'

    def get_object(self, slug=None):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)#get the profile by using the profile slug 
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact= self.request.user)
        profile = Profile.objects.get(user=user)
        context['profile'] = profile
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []

        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        context['posts'] = self.get_object().get_all_authors_posts()
        context['len_posts'] = True if len(self.get_object().get_all_authors_posts()) > 0 else False        
        return context
    




class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'
    context_object_name = 'qs'


    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact= self.request.user)
        profile = Profile.objects.get(user=user)
        context['profile'] = profile
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []

        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False

        if len(self.get_queryset()) == 0:
            context['is_empty'] = True
            
        return context

@login_required
def send_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')

@login_required
def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
    
        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))   
        )

        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/profiles/templates/profiles/detail.html

{% extends 'base.html' %}

{% block title%}profile detail{% endblock title%}

{% block content %}
{% url 'posts:main-post-view' as path_to_posts %}
    <div class="ui one column stackable page grid" style="color: white;background-color:#363062;">
        <br>
        <div class="row">
            <div class="four wide column">
                <img class="ui small rounded image" src="{{object.avatar.url}}" alt="" >
                <h1>{{object.user}}</h1>
                <div class="ui vertical fluid menu"style="color: white;background-color:#4D4C7D;">
                    <div class="item" style="color: white;">
                        Posts
                        <div class="ui label">
                            {{object.get_posts_no}}
                        </div>
                    </div>
                    <div class="item" style="color: white;">
                        Likes given
                        <div class="ui label">
                            {{object.get_likes_given_no}}
                        </div>
                    </div>
                    <div class="item" style="color: white;">
                        Likes Received
                        <div class="ui label">
                            {{object.get_likes_recieved_no}}
                        </div>
                    </div>
                    <div class="item" style="color: white;">
                        Friends
                        <div class="ui label">
                            {{object.get_friends_no}}
                        </div>
                    </div>
                </div>

                    {% if object.user not in rel_receiver and object.user not in rel_sender %}
                        <form action="{% url 'profiles:send_invite' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{object.pk}}">
                            <button type="submit" class="ui positive basic button  mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                        </form>
                    {% endif %}

                    <!-- friend requesting send and Waiting for approval -->
                    {% if object.user in rel_receiver and request.user not in object.friends.all %}
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{object.pk}}">
                            <button type="submit" class="ui disabled button mb-5 w-big"><i class="user icon "></i>Waiting for approval</button>   
                        </form>
                    {% endif %}

                     <!-- already in the user friend lists    -->
                    {% if request.user in object.friends.all %}
                        <form action="{% url 'profiles:remove-friend' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{object.pk}}">
                            <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove</button>
                        </form>
                    {% endif %}

            </div>
            <div class="twelve wide column">
                {% if len_posts %}
                    {% for post in posts %}
                        <div class="segment ui fluid" style="color: white;background-color:#4D4C7D">
                            {{post.content|safe}}
                            {% if post.image %}
                            <div class="ui fluid image">
                                <img src="{{post.image.url}}" alt="">
                            </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% else %}
                    <h1>No posts to show</h1>
                {% endif %}
            </div> 
        </div>
    </div>
{% endblock content %}
{% block scripts %} 
    <script>
        $( document ).ready(function() {
            let display = false
            $(".cmt_btn").click(function () {
                if (display===false) {
                    $(this).next(".comment-box").show("slow");
                    display=true
                } else {
                    $(this).next(".comment-box").hide("slow");
                    display=false
                }  
            });

            $('.like-form').submit(function(e){
                e.preventDefault()
                
                const post_id = $(this).attr('id')
                
                const likeText = $(`.like-btn${post_id}`).text()
                const trim = $.trim(likeText)

                const url = $(this).attr('action')
                
                let res;
                const likes = $(`.like-count${post_id}`).text()
                const trimCount = parseInt(likes)
                
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                        'post_id':post_id,
                    },
                    success: function(response) {
                        if(trim === 'Unlike') {
                            $(`.like-btn${post_id}`).text('Like')
                            res = trimCount - 1
                        } else {
                            $(`.like-btn${post_id}`).text('Unlike')
                            res = trimCount + 1
                        }

                        $(`.like-count${post_id}`).text(res)
                    },
                    error: function(response) {
                        console.log('error', response)
                    }
                })

            })
        });
    </script>
{% endblock scripts %}

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/profiles/templates/profiles/friends.html
{% extends 'base.html' %}

{% block title%}friends{% endblock title%}

{% block content %}
    {% if is_empty %}
        <h1>You don't have any friends.</h1>
        <p><a href="{% url 'invite_profile_view' %}">click here </a>to check out and add friends...</p>
    {% endif %}

    {% for obj in qs %}
            <div class="ui segment" style="color: white;background-color:#363062;">
                <div class="ui grid">
                    <div class="row">
                        <div class="three wide column">
                            <img src="{{obj.avatar.url}}" alt="" class="ui small circular image">
                        </div>
                        <div class="thirteen wide column">
                            <h3>{{obj.user}}</h3>
                            <p>{{obj.bio}}</p>
                            <a href="{{obj.get_absolute_url}}">
                            <button class="ui primary button w-big">See profile</button>
                            </a>
                    
                        <!-- add to friends lists -->
                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                            <form action="{% url 'profiles:send_invite' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                <button type="submit" class="ui positive basic button w-big"><i class="plus square icon"></i>Add to friends</button>
                            </form>
                        {% endif %}

                        <!-- friend requesting send and Waiting for approval -->
                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <form action="" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                <button type="submit" class="ui disabled button w-big"><i class="user icon "></i>Waiting for approval</button>   
                            </form>
                        {% endif %}

                        <!-- already in the user friend lists    -->
                        {% if request.user in obj.friends.all %}
                            <form action="{% url 'profiles:remove-friend' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                <button type="submit" class="ui negative basic button  w-big"><i class="minus square icon"></i>Remove</button>
                            </form>
                        {% endif %}
                    </div>

                    </div>
                </div>
            </div>
    {% endfor %}
{% endblock content %}

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/profiles/templates/profiles/my_invites.html
{% extends 'base.html' %}

{% block title%}my invites {% endblock title%}

{% block content %}

    {% if is_empty %}
    <h1>No friend requests</h1>
    {% endif %}

    <ul>
        {% for obj in qs %}
            <div class="ui segment" style="color: white;background-color:#363062;">
                <div class="ui grid">
                    <div class="row">
                        <div class="three wide column">
                            <img src="{{ obj.avatar.url }}" alt="" class="ui small circular image">
                        </div>
                        <div class="thirteen wide column">
                            <h3>{{obj.user}}</h3>
                            <p>{{ obj.bio }}</p>
                            <a href="{{obj.get_absolute_url}}"><button class="ui primary button w-big ">See profile</button></a>

                            <form action="{% url 'profiles:accept_invitation' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{ obj.pk }}">
                                <button type="submit" class="ui positive basic button w-big "><i class="check icon ">Accept invite</i></button>
                               
                            </form>
                            <form action="{% url 'profiles:reject_invitation' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{ obj.pk }}">
                                <button type="submit" class="ui negative basic button w-big "><i class="close icon ">Reject invite</i></button>
                            </form> 
                        </div>

                    </div>
                </div>
            </div>
        {% endfor %}
    </ul>
{% endblock content %}

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title%}my invites {% endblock title%}

{% block content %}
   {% if is_empty %}
        No profiles to interact with
   {% endif %}

   {% for obj in object_list %}
        <div class="ui segment" style="color: white;background-color:#363062;">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img src="{{obj.avatar.url}}" alt="" class="ui small circular image">
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="{{obj.get_absolute_url}}">
                        <button class="ui primary button w-big">See profile</button>
                        </a>
                   
                    <!-- add to friends lists -->
                    {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                        <form action="{% url 'profiles:send_invite' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                            <button type="submit" class="ui positive basic button w-big"><i class="plus square icon"></i>Add to friends</button>
                        </form>
                    {% endif %}

                    <!-- friend requesting send and Waiting for approval -->
                    {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                            <button type="submit" class="ui disabled button w-big"><i class="user icon "></i>Waiting for approval</button>   
                        </form>
                    {% endif %}

                     <!-- already in the user friend lists    -->
                    {% if request.user in obj.friends.all %}
                        <form action="{% url 'profiles:remove-friend' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                            <button type="submit" class="ui negative basic button  w-big"><i class="minus square icon"></i>Remove</button>
                        </form>
                    {% endif %}
                </div>

                </div>
            </div>
        </div>
   {% endfor %}
{% endblock content %}

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/profiles/templates/profiles/to_invite_list.html
{% extends 'base.html' %}

{% block title%}my invites {% endblock title%}

{% block content %}
    <ul>
        {% for item in qs %}
            <li>{{ item }}</li>
        {% endfor %}
    </ul>
{% endblock content %}