socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/bffbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home_view'),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include("profiles.urls", namespace="profiles")),
    path('posts/', include("posts.urls", namespace="posts"))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/posts/urls.py
from django.urls import path
from .views import post_comment_create_list_view, like_unlike_post, PostDeleteView, PostUpdateView, CommentDeleteView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_list_view, name='main-post-view'),
    path('liked', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('comment/<pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
]   

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view, 
    invites_received_view, 
    ProfileListView, 
    ProfileDetailView,
    invite_profiles_list_view,
    send_invitation,
    remove_from_friends,
    accept_invitation,
    reject_invitation,
    friends,
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name="all_profile_view"),
    path('myprofile/', my_profile_view, name="my_profile_view"),
    path('my-invites/', invites_received_view, name="my_invites_view"),
    path('to-invite/', invite_profiles_list_view, name="invite_profile_view"),
    path('send-invite/', send_invitation, name="send_invite"),
    path('remove-friend/', remove_from_friends, name="remove-friend"),
    path('<slug>', ProfileDetailView.as_view(), name="profile_detail_view"),  
    path('accept/', accept_invitation, name="accept_invitation"),
    path('reject/', reject_invitation, name="reject_invitation"), 
    path('friends/', friends, name="friends_list"),
]

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}


{% block content %}
    
{% endblock content %}

{% block script %}
   
  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

{% endblock script%}

socialmedia-main (DIPLOMA PROJECT)/socialmedia-main/templates/main/navbar.html
{% url 'home_view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my_profile_view' as path_to_my_profile %}
{% url 'profiles:my_invites_view' as path_to_my_invites %}
{% url 'profiles:invite_profile_view' as path_to_invites %}
{% url 'profiles:all_profile_view' as path_to_all_profiles %}
{% url 'profiles:friends_list' as path_to_all_friends %}

<header class="mb-4">
    {% if request.user.is_authenticated %}
    <div class="p-4 my_nav text-white ">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="{{path_to_posts}}" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <svg id="emoji" viewBox="0 0 60 60" version="1.1" xmlns="http://www.w3.org/2000/svg"> 
              <g id="hair"/>
              <g id="skin">
                <path fill="#FCEA2B" d="M18.6575,19.2409c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115c-1.6927,0.9684-2.2799,3.1256-1.3115,4.8183 c0.1552,0.2714,0.3458,0.5209,0.5667,0.742l11.5324,15.0998l2.6883,3.3878l-7.8906-10.3314 c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115s-2.2799,3.1256-1.3115,4.8183c0.1552,0.2714,0.3458,0.5209,0.5667,0.7421 L21.752,46.226l6.2707,7.899c5.467,6.2731,14.5147,5.9306,20.7863,0.465c3.6045-3.1684,5.9226-7.5482,6.5154-12.3105 c0.3858-4.2326,0.807-15.301,0.807-15.301c-0.1826-2.6008-3.1353-4.5234-3.5158-3.1802l-4.8939,9.7575l-3.3657-4.2224 l3.3657,4.2224l-3.3657-4.2224L30.8909,12.1248c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115s-2.2799,3.1256-1.3115,4.8183 c0.1552,0.2714,0.3458,0.5209,0.5667,0.742l4.2488,5.5631L36,30.4167L22.581,12.7366c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115 s-2.2799,3.1256-1.3116,4.8183c0.1552,0.2714,0.3458,0.5209,0.5667,0.7421L31.6894,36"/>
              </g>
              <g id="skin-shadow"/>
              <g id="color"/>
              <g id="line">
                <path fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.6575,19.2409 c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115c-1.6927,0.9684-2.2799,3.1256-1.3115,4.8183 c0.1552,0.2714,0.3458,0.5209,0.5667,0.742l11.5324,15.0998l2.6883,3.3878l-7.8906-10.3314 c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115s-2.2799,3.1256-1.3115,4.8183c0.1552,0.2714,0.3458,0.5209,0.5667,0.7421 L21.752,46.226l6.2707,7.899c5.467,6.2731,14.5147,5.9306,20.7863,0.465c3.6045-3.1684,5.9226-7.5482,6.5154-12.3105 c0.3858-4.2326,0.807-15.301,0.807-15.301c-0.1826-2.6008-3.1353-4.5234-3.5158-3.1802l-4.8939,9.7575l-3.3657-4.2224 l3.3657,4.2224l-3.3657-4.2224L30.8909,12.1248c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115s-2.2799,3.1256-1.3115,4.8183 c0.1552,0.2714,0.3458,0.5209,0.5667,0.742l4.2488,5.5631L36,30.4167L22.581,12.7366c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115 s-2.2799,3.1256-1.3116,4.8183c0.1552,0.2714,0.3458,0.5209,0.5667,0.7421L31.6894,36"/>
                <path fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M11.6726,42.8719c0,2.5663,1.747,4.6428,3.9059,4.6428"/>
                <path fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M7.0614,42.4369c0,5.5959,3.8094,10.1241,8.5171,10.1241"/>
                <path fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M45.2619,21.2377c0-2.5663-1.747-4.6428-3.9059-4.6428"/>
                <path fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M49.8731,21.6727c0-5.5959-3.8094-10.1241-8.5171-10.1241"/>
              </g>
            </svg>
          </a>

          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li><a class="nav-link px-2 text-white{% if request.path == path_to_posts %}active{% endif %}" href="{{path_to_posts}}">Home</a></li>
            <li><a class="nav-link px-2 text-white{% if request.path == path_to_all_profiles %}active{% endif %}" href="{{path_to_all_profiles}}" aria-current="page">All Users</a></li>
            <li><a class="nav-link px-2 text-white{% if request.path == path_to_all_friends%}active{% endif %}"href="{{path_to_all_friends}}">Friends</a></li>
            <li><a class="nav-link px-2 text-white{% if request.path == path_to_my_invites %}active{% endif %}" href="{{path_to_my_invites}}">Invites <div class="badge bg-secondary">{{invites_num}}</div></a></li>
              {% if request.user.is_authenticated %}
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
                  <img src="{{picture.url}}" alt="mdo" width="32" height="32" class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                  <li><a class="dropdown-item {% if request.path == path_to_my_profile %}active{% endif %}" href="{{path_to_my_profile}}">Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>    
                </ul>       
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </div>
{% else %}
  <div class="px-4 py-5 my-3 text-center">
    <svg id="emoji" viewBox="0 0 60 60" version="1.1" xmlns="http://www.w3.org/2000/svg"> 
      <g id="hair"/>
      <g id="skin">
        <path fill="#FCEA2B" d="M18.6575,19.2409c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115c-1.6927,0.9684-2.2799,3.1256-1.3115,4.8183 c0.1552,0.2714,0.3458,0.5209,0.5667,0.742l11.5324,15.0998l2.6883,3.3878l-7.8906-10.3314 c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115s-2.2799,3.1256-1.3115,4.8183c0.1552,0.2714,0.3458,0.5209,0.5667,0.7421 L21.752,46.226l6.2707,7.899c5.467,6.2731,14.5147,5.9306,20.7863,0.465c3.6045-3.1684,5.9226-7.5482,6.5154-12.3105 c0.3858-4.2326,0.807-15.301,0.807-15.301c-0.1826-2.6008-3.1353-4.5234-3.5158-3.1802l-4.8939,9.7575l-3.3657-4.2224 l3.3657,4.2224l-3.3657-4.2224L30.8909,12.1248c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115s-2.2799,3.1256-1.3115,4.8183 c0.1552,0.2714,0.3458,0.5209,0.5667,0.742l4.2488,5.5631L36,30.4167L22.581,12.7366c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115 s-2.2799,3.1256-1.3116,4.8183c0.1552,0.2714,0.3458,0.5209,0.5667,0.7421L31.6894,36"/>
      </g>
      <g id="skin-shadow"/>
      <g id="color"/>
      <g id="line">
        <path fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.6575,19.2409 c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115c-1.6927,0.9684-2.2799,3.1256-1.3115,4.8183 c0.1552,0.2714,0.3458,0.5209,0.5667,0.742l11.5324,15.0998l2.6883,3.3878l-7.8906-10.3314 c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115s-2.2799,3.1256-1.3115,4.8183c0.1552,0.2714,0.3458,0.5209,0.5667,0.7421 L21.752,46.226l6.2707,7.899c5.467,6.2731,14.5147,5.9306,20.7863,0.465c3.6045-3.1684,5.9226-7.5482,6.5154-12.3105 c0.3858-4.2326,0.807-15.301,0.807-15.301c-0.1826-2.6008-3.1353-4.5234-3.5158-3.1802l-4.8939,9.7575l-3.3657-4.2224 l3.3657,4.2224l-3.3657-4.2224L30.8909,12.1248c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115s-2.2799,3.1256-1.3115,4.8183 c0.1552,0.2714,0.3458,0.5209,0.5667,0.742l4.2488,5.5631L36,30.4167L22.581,12.7366c-0.9683-1.6927-3.1256-2.2799-4.8183-1.3115 s-2.2799,3.1256-1.3116,4.8183c0.1552,0.2714,0.3458,0.5209,0.5667,0.7421L31.6894,36"/>
        <path fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M11.6726,42.8719c0,2.5663,1.747,4.6428,3.9059,4.6428"/>
        <path fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M7.0614,42.4369c0,5.5959,3.8094,10.1241,8.5171,10.1241"/>
        <path fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M45.2619,21.2377c0-2.5663-1.747-4.6428-3.9059-4.6428"/>
        <path fill="none" stroke="#000000" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M49.8731,21.6727c0-5.5959-3.8094-10.1241-8.5171-10.1241"/>
      </g>
     </svg>
    <h1 class="display-5 fw-bold">Hello</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">Welcome to our social media web app. Please login or Sign up to continue...</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a href="{% url 'account_login' %}"><button type="button" class="btn btn-primary btn-lg px-4 gap-3">Login</button></a>
        <a href="{% url 'account_signup' %}"><button type="button" class="btn btn-dark btn-lg px-4">Signup</button></a>
      </div>
    </div>
  </div>

{% endif %}
</header>